name: Update Shadowrocket Rules

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨自动运行
  workflow_dispatch: # 支持手动触发

# 显式赋予写入权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Convert
        run: |
          # 设置当前时间（格式：yyyy-MM-dd HH:mm）
          now=$(date +'%Y-%m-%d %H:%M')

          # 定义需要转换的文件列表
          files=("accelerated-domains.china" "google.china" "apple.china")

          for file in "${files[@]}"; do
            # 下载原始文件
            curl -sSL "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/$file.conf" -o "$file.conf"
          done

          # 下载官方的 Makefile
          curl -sSL "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/Makefile" -o "Makefile"

          # 提取纯域名
          make raw

          for file in "${files[@]}"; do
            # 获取规则行数和最终文件名
            count=$(grep -c -E -v '^\s*(#|$)' "$target_file")
            final_filename="$file.list"

            # 组装 Header 和内容
            {
              echo "#!name=$final_filename"
              echo "#!homepage=https://github.com/OriginVorfeed/shadowrocket-china-list"
              echo "#!desc=Rules:$count Created:$now Publisher:OriginVorfeed"
              echo "[Rule]"
              # 转换为 Shadowrocket 格式 (DOMAIN-SUFFIX,域名,DIRECT)
              sed -e 's|\(.*\)|DOMAIN-SUFFIX,\1,DIRECT|' "$file.raw.txt"
            } > "$final_filename"

            # 清理中间文件
            rm "$file.conf" "$file.raw.txt"
          done

      - name: Git push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add *.list
          git commit -m "Update rules: $(date)" || exit 0
          git push
